### ISSUE TITLE
add weapon type as categories on the patterns tab

### ISSUE THREAD

**Issue by tednaleid** [rslifka/vault-zero#18]
The Patterns tab is my most used feature in Vault Zero. 

Now that we've got many seasons and activities behind us, it's pretty rare that I look at historical categories.  Many of those sources aren't available anymore or are things I gave up grinding on as I'd gotten the things I wanted

![CleanShot 2023-09-04 at 12 41 29](https://github.com/rslifka/vault-zero/assets/5231/37419c51-e78e-455e-b9f3-71b62abd0605)

What I often want these days is to look at a weapon category (hand cannons, smgs, rocket launchers, etc) to see what craftable options there are.

A few seasons ago I gave up on crafting a god roll of every weapon, so there are often patterns that I could craft when the meta changes.  

This season hand cannons are great and I'm looking for hand cannons I could possibly craft.  I can't easily do that in VZ and end up using DIM for this feature with a query on the "Records" tab of `is:craftable is:handcannon`.

![CleanShot 2023-09-04 at 12 49 34](https://github.com/rslifka/vault-zero/assets/5231/bad850cf-c05c-46ee-a04e-91942e731fbc)

That's missing the nice features of VZ to show which I've completed, or how close I am to finishing the pattern of each.  It also doesn't show the element of the weapon on the icon like VZ.

It'd be nice to have these categories in VZ, possibly replacing the historical categories, or else just below them.

**Comment by rslifka** [comment]
Added Pattern browsing in 1.3.0 🎉 😄
