### ISSUE TITLE
Add Kill Count to weapon detail

### ISSUE THREAD

**Issue by tednaleid** [rslifka/vault-zero#55]
Kill Count is in DIM and it has a couple of uses that make it something that I miss in VZ.

I use it when sharing with other folks to show how much I'm using a weapon, sometimes numbers in the 4+ digits get a reaction.

Also, when I'm trying to figure out which weapon is the one I most commonly use, I'll pick the one with the higher kill count.

![CleanShot 2024-02-29 at 12 43 16](https://github.com/rslifka/vault-zero/assets/5231/61630b98-e6eb-49ba-8207-65795e33dbd9)

**Comment by rslifka** [comment]
![CleanShot 2024-04-02 at 21 26 53@2x](https://github.com/rslifka/vault-zero/assets/231435/c58812aa-79f9-405c-9a79-0a8cff0deb68)
