### ISSUE TITLE
Add activity location to Activity detail page

### ISSUE THREAD

**Issue by tednaleid** [rslifka/vault-zero#6]
It'd be nice to add the location of an activity on the director.

I've got most lost sectors memorized, but letting folks know that Perdition is a lost sector on Europa will save people some time.

It looks like it's part of the data set, at least for the lost sector there is a `destinationHash` value that could be extracted and displayed: https://data.destinysets.com/i/Activity:1070981425

![cleanshot_2023-04-10_at_14 23 38](https://user-images.githubusercontent.com/5231/230983199-c2f468c7-c828-4aa9-8888-e30f9b44e569.png)
![CleanShot 2023-04-10 at 14 41 04](https://user-images.githubusercontent.com/5231/230983512-f0824022-7fe8-4220-90ed-763366638c59.png)

**Comment by rslifka** [comment]
Implemented as of https://github.com/rslifka/reckoner-app/commit/5ced040ee6329e664c19927fd4cfb4caa3035942
