### ISSUE TITLE
Add Lost Sector rewards

### ISSUE THREAD

**Issue by tednaleid** [rslifka/vault-zero#7]
One of the main reasons I look at the daily lost sector is to see what slot is dropping today (arms, chest, head, legs).

Currently, the UI does not display the reward for lost sectors.  It would be nice if the reward slot was listed on the detailed UI for legend/master lost sectors, something like this:

![cleanshot_2023-04-12_at_16 18 33](https://user-images.githubusercontent.com/5231/231591707-4de1c254-6c25-4f7c-9f7a-e8694cfbc2a7.png)

Unfortunately, it does not look like this is available in the [JSON for the lost sector activity](https://data.destinysets.com/i/Activity:1163502303).  It has all rewards listed, not just the slot available today.  There is also not a separate field that determines which reward is active as far as I can tell.

![cleanshot_2023-04-12_at_16 19 52](https://user-images.githubusercontent.com/5231/231591854-76199e1b-e66b-400b-9e2a-4c084b15a3a2.png)

After talking with Slif, it turns out that the lost sector code for today is already a hard-coded rotator list:
![screenshot_2023-04-12_at_2 31 38_pm_720](https://user-images.githubusercontent.com/5231/231592002-5cf2f45f-36b4-4864-b41c-b236300dad8b.png)

One idea would be to enhance this rotator list code to have some sort of enum/list for the reward that'll rotate through `[arms, chest, head, legs]` and uses the same `rotationStart` variables in the image above.  The number of days "today" is offset from the `rotationStart` modulus 4 should pick the right reward.

This rotation order is documented on the todayindestiny site (where they likely have a similar hard-coded list): https://www.todayindestiny.com/ls_calendar
![cleanshot_2023-04-12_at_16 34 42](https://user-images.githubusercontent.com/5231/231592548-2cbdbe3b-0a0c-4232-a55b-fc9813c61d1e.png)

**Comment by rslifka** [comment]
This is currently only partially implemented. The legendary weapon rewards have been added as of https://github.com/rslifka/reckoner-app/commit/543a0e1ec156126b7d842b143f6acca324192e5f

**Comment by rslifka** [comment]
It only took a year, sorry Ted 😄
