### ISSUE TITLE
"Iron Banner Gear Equipped" not updating in sync with reset estimate

### ISSUE THREAD

**Issue by trevorstinson** [rslifka/vault-zero#79]
In the reputation dashboard, the reset estimates (wins until reset, etc.) are updating when the app refreshes, but "Iron Banner Gear Equipped" and "Iron Banner Emblem" are not updating. The correct values are shown when opening the detail view.

Dashboard showing updated estimates, but stale gear info:

<img width="1163" alt="Screenshot 2024-07-14 at 14 04 57" src="https://github.com/user-attachments/assets/677ef166-553c-4e8f-bb60-9b535b4d4b8c">

Detail view showing all info up to date:

<img width="1163" alt="Screenshot 2024-07-14 at 14 05 01" src="https://github.com/user-attachments/assets/b5f2932c-7c17-402a-aadc-05fdf9217893">

**Comment by rslifka** [comment]
Fixed in 2.0!
